workflows:
  unity-ios-unsigned:
    name: Unity iOS Unsigned IPA
    instance_type: mac_mini_m2

    environment:
      groups:
        - unity
      xcode: latest
      cocoapods: default
      vars:
        UNITY_PATH: "/Applications/Unity/Hub/Editor/2023.1.0f1/Unity.app/Contents/MacOS/Unity"

    scripts:
  - name: Build Xcode project (no signing)
    script: |
      cd Unity-iPhone
      xcodebuild -scheme Unity-iPhone \
        -project Unity-iPhone.xcodeproj \
        -configuration Release \
        -archivePath build/Unity-iPhone.xcarchive archive \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      xcodebuild -exportArchive \
        -archivePath build/Unity-iPhone.xcarchive \
        -exportPath build/ipa \
        -exportOptionsPlist ExportOptions.plist \
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Build Xcode project (no signing)
        script: |
          cd build/ios
          xcodebuild -scheme Unity-iPhone \
            -project Unity-iPhone.xcodeproj \
            -configuration Release \
            -archivePath build/Unity-iPhone.xcarchive archive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
            -archivePath build/Unity-iPhone.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ../ExportOptions.plist \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    artifacts:
      - build/ios/build/ipa/*.ipa
      - build/ios/build/ipa/*.xcarchive
