# اسم سير العمل (workflow)
workflows:
  unity-ios-build:
    name: Unity iOS Build

    # إعدادات بيئة البناء
    environment:
      xcode: latest
      # تعريف متغيرات البيئة التي تم إعدادها في Codemagic
      groups:
        - apple_signing
      
    # الأوامر التي سيتم تنفيذها لعملية البناء
    scripts:
      - name: Build Unity iOS Project
        script: |
          echo "Building Unity iOS Project..."
          
          # تأكد من أن اسم المشروع والـ scheme صحيحان
          xcodebuild build \
            -workspace "Unity-iPhone.xcworkspace" \
            -scheme "Unity-iPhone" \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            
            # هذه الأوامر تخبر Xcode بأن يترك التوقيع لـ Codemagic
            # يجب أن تكون هذه الأوامر في سطر واحد
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            CODE_SIGNING_REQUIRED=NO \
            
            # هذه الأوامر تُعطل الشهادات والبروفايلات اليدوية
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM=""
            
    # تحديد الملفات التي يجب حفظها كـ artifacts
    artifacts:
      # هذا المسار هو الأكثر شيوعًا للملف النهائي
      - 'build/Unity-iPhone.ipa'
      - 'build/Release-iphoneos/Unity-iPhone.ipa'
