# اسم سير العمل (workflow)
workflows:
  unity-ios-build:
    name: Unity iOS Build

    # إعدادات بيئة البناء
    environment:
      xcode: latest
      # تعريف متغيرات البيئة التي تم إعدادها في Codemagic
      groups:
        - apple_signing
      
    # الأوامر التي سيتم تنفيذها لعملية البناء
    scripts:
      - name: Build Unity iOS Project
        script: |
          echo "Building Unity iOS Project..."
          
          # تم تغيير -workspace إلى -project
          xcodebuild build \
            -project "Unity-iPhone.xcodeproj" \
            -scheme "Unity-iPhone" \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            CODE_SIGNING_REQUIRED=NO \
            
            PROVISIONING_PROFILE_SPECIFIER="" \
            DEVELOPMENT_TEAM=""
            
    # تحديد الملفات التي يجب حفظها كـ artifacts
    artifacts:
      - 'build/Unity-iPhone.ipa'
      - 'build/Release-iphoneos/Unity-iPhone.ipa'
