workflows:
  unity_ios_ipa:
    name: Unity iOS IPA
    max_build_duration: 60
    environment:
      flutter: none
      xcode: latest
    scripts:
      - name: Build Unity iOS project
        script: |
          echo "Building Unity iOS Project..."
          cd $CM_BUILD_DIR
          xcodebuild -project Unity-iPhone.xcodeproj -scheme Unity-iPhone -configuration Release -archivePath $CM_BUILD_DIR/build/Unity-iPhone.xcarchive archive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/Unity-iPhone.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR/build/IPA
    artifacts:
      - build/IPA/*.ipa
