workflows:
  ios-try-unsigned:
    name: Try build unsigned IPA
    environment:
      xcode: latest
    scripts:
      - name: Try build (no signing)
        script: |
          set -e
          # build directory
          BUILD_DIR="$CM_BUILD_DIR/build/Release-iphoneos"
          mkdir -p "$BUILD_DIR"
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme "Unity-iPhone" \
            -configuration Release \
            -sdk iphoneos \
            BUILD_DIR="$BUILD_DIR" \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build || true

          if [ -d "$BUILD_DIR/Unity-iPhone.app" ]; then
            echo "App built, packaging IPA..."
            cd "$BUILD_DIR"
            mkdir -p Payload
            cp -R Unity-iPhone.app Payload/
            zip -r UnsignedApp.ipa Payload
            echo "IPA ready: $BUILD_DIR/UnsignedApp.ipa"
          else
            echo "No .app produced; build likely required signing. See logs."
            exit 2
          fi
    artifacts:
      - build/Release-iphoneos/UnsignedApp.ipa
