workflows:
  unity-ios-unsigned:
    name: Unity iOS Unsigned Build
    instance_type: mac_mini_m2 # أو أي جهاز Mac آخر متوفر
    environment:
      unity: 2022.3.10f1 # استبدل بإصدار Unity الذي تستخدمه
    scripts:
      - name: Activate Unity license
        script: |
          /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub \
            -- --headless \
            -quit \
            -batchmode \
            -username "$UNITY_USERNAME" \
            -password "$UNITY_PASSWORD" \
            -serial "$UNITY_SERIAL"
      - name: Build Xcode project from Unity
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -quit \
            -batchmode \
            -projectPath . \
            -executeMethod BuildScript.PerformIOSBuild
      - name: Build unsigned .ipa
        script: |
          cd build/ios # انتقل إلى مجلد Xcode الذي تم إنشاؤه
          xcodebuild archive \
            -scheme Unity-iPhone \
            -archivePath ../../build/ios/archive/Unity-iPhone.xcarchive \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
          xcodebuild -exportArchive \
            -archivePath ../../build/ios/archive/Unity-iPhone.xcarchive \
            -exportPath ../../build/ios/ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
