workflows:
  unity_ios_unsigned:
    name: Unity iOS Unsigned IPA
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Build Unity iOS project (no signing)
        script: |
          echo "🔨 Starting Unity iOS build without signing..."
          # بناء مشروع iOS بدون أرشفة
          xcodebuild \
            -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -configuration Release \
            -sdk iphoneos \
            build

          echo "📦 Packaging IPA..."
          cd build/Release-iphoneos
          mkdir Payload
          cp -r Unity-iPhone.app Payload/
          zip -r UnsignedApp.ipa Payload

          echo "✅ IPA created at: build/Release-iphoneos/UnsignedApp.ipa"
    artifacts:
      - build/Release-iphoneos/UnsignedApp.ipa
