workflows:
  ios-unsigned:
    name: Build Unity iOS (Unsigned IPA)
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
    scripts:
      - name: Build Xcode project (no signing)
        script: |
          xcodebuild -scheme "$XCODE_SCHEME" \
            -project "$XCODE_WORKSPACE" \
            -configuration Release \
            -archivePath build/Unity-iPhone.xcarchive archive \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
            -archivePath build/Unity-iPhone.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - "your_email@example.com"
